### ISSUE TITLE
add the command `debug pingApi` to the CLI for checking the connection and data of Api1

### ISSUE THREAD

**Issue by Jon-Kle** [Jon-Kle/DB-Manager#4]

**Comment by LeeLux** [comment]
What should it reply if something isn't working correctly? use the exception name and what it means or  what specific?

**Comment by Jon-Kle** [comment]
If everything works, write something like "connection works". If not, write a message for every error type (ApiConnectionError, DataIncompleteError, ...)
I think you can pretty much use the excepts and the messages from preeloop() but without the extra hints like "make sure your internet connection is working!"

**Comment by LeeLux** [comment]
done and in the branch. Look at it and say if the is ok.

**Comment by Jon-Kle** [comment]
Can you create a pull request?
