### ISSUE TITLE
Improve command name logic

### ISSUE THREAD

**Issue by Jon-Kle** [Jon-Kle/DB-Manager#42]
By renaming and rearranging some commands in the CLI, the logic of some commands can be greatly improved.

- move `pingDB` over to `do_database` (former do_mendDB) and rename it to `ping`
- create the new commands `do_api1` and `do_api2`
- move `pingApi` over to `do_api1` and rename it to `ping`
- move `request api1` over to `do_api1` and rename it to request
- rename `do_request api2` into `do_api2 request`
- (you could also add a ping option for api2)
- Please rearrange the doc-strings accordingly

In the future, options could be added, that call do_config() with the preselected section depending on the command

**Comment by LeeLux** [comment]
What do you mean by "doc-strings" @Jon-Kle ?

**Comment by Jon-Kle** [comment]
The documentation strings are the comments that use `''' '''` that stand at the start of every class and function.

**Comment by Jon-Kle** [comment]
update: `do_request` should be merged into debug
that means these two lines in the first message:
- move` request api1` over to `do_api1` and rename it to `request`
- rename `do_request api2` into `do_api2 request`

should be changed into:
- move` request api1` over to `do_debug` and rename it to `api1Request`
- rename `do_request api2` into `do_debug api2Request`

(This is not a homework or something, I am just writing that down. Mainly for myself)
