### ISSUE TITLE
add windows compatibility for restart()

### ISSUE THREAD

**Issue by Jon-Kle** [Jon-Kle/DB-Manager#9]
The restart command is not working on windows.
The Solution for Mac is:
`os.execl(sys.executable, 'python3', __file__, 'restart')`

**Comment by Jon-Kle** [comment]
@LeeLux could you send me the exact error msg you get when trying to use restart?

**Comment by LeeLux** [comment]
PS C:\Users\Name\Desktop\Wetterstation Projekt\DB-Manager\src> python3: can't open file 'C:\\Users\\Name\\Desktop\\Wetterstation': 
[Errno 2] No such file or directory

**Comment by Jon-Kle** [comment]
Could you @LeeLux check out the branch restart-compatibility and test if restart is working on windows now?

**Comment by LeeLux** [comment]
yes `os.execl(sys.executable, sys.executable, path, 'restart')`is working for me just fine

**Comment by Jon-Kle** [comment]
Could you @LeeLux check out the branch again and show me the error message if there is one?

**Comment by LeeLux** [comment]
`os.execl(sys.executable, path, sys.argv[0], 'restart')` **is working**
```Use "help" for a list of commands
---(DB-Manager)> restart
['main.py']
PS C:\Users\Leander\Desktop\Wetterstation Projekt\DB-Manager\src>     -- DB-Manager --

 API1 request: failed!
  Some data values are missing:```
